[metadata]
format.version = "1.1"

[versions]
assertj = "3.26.3"
checkstyle = "10.21.0"
edc = "0.11.0-SNAPSHOT"
jackson = "2.18.2"
jetbrainsAnnotation = "26.0.1"
jakarta-ws-rs = "4.0.0"
jupiter = "5.11.3"
mockito = "5.14.2"
swagger = "2.2.22"
swagger-parser = "2.1.24"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
edc-runtime-metamodel = { module = "org.eclipse.edc:runtime-metamodel", version.ref = "edc" }
edc-core-spi = { module = "org.eclipse.edc:core-spi", version.ref = "edc" }
j2html = { module = "com.j2html:j2html", version = "1.6.0" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jakarta-ws-rs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakarta-ws-rs" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotation" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter" }
markdown-gen = { module = "net.steppschuh.markdowngenerator:markdowngenerator", version = "1.3.1.1" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
plugin-checksum = { module = "gradle.plugin.org.gradle.crypto:checksum", version = "1.4.0" }
plugin-nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version = "2.0.0" }
plugin-openapi-merger = { module = "com.rameshkp:openapi-merger-gradle-plugin", version = "1.0.5" }
plugin-swagger = { module = "io.swagger.core.v3:swagger-gradle-plugin", version.ref = "swagger" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger-parser" }

[bundles]

[plugins]
publish = { id = "com.gradle.plugin-publish", version = "1.3.0" }
